### ISSUE TITLE
Thumbnails madness

### ISSUE THREAD

**Issue by lord-kraken** [Phrynohyas/eve-o-preview#104]
Good day!
I'm facing few issues with the latest version (3.1.0)
1. No thumbnails in game at all, until "Hide previews when EVE client is not active" checkbox checked.
2. If check it - there are thumbnails in game, but once it hovered - it just collapse all EVE clients, so I need to use windows system tray for get back to game. After switch to game - no thumbnails showed again, so I need to collapse all windows again.
[EVE-O Preview.txt](https://github.com/Phrynohyas/eve-o-preview/files/1691706/EVE-O.Preview.txt)

**Comment by Phrynohyas** [comment]
Kind of odd, because
>  `once it hovered - it just collapse all EVE clients` - 
there is just no code (yet) to minimize all clients

Do you by any chance have any 'Ease Of Access' features enabled? F.e. the "Activate a window by hovering over it with the mouse" one?

**Comment by lord-kraken** [comment]
nop

**Comment by lord-kraken** [comment]
lets clear it up, once thumb hovered - its switch to browser, as its open for me (if it could help any way)

**Comment by lord-kraken** [comment]
UPD:
fixed everything by setting game to "windowed mode". if it intended to be in "windowed mode" for correct behavior - pls, make a note somewhere, maybe. 
thanks.
