### ISSUE TITLE
Make zooming actually zoom, not enlarge thumbnail size

### ISSUE THREAD

**Issue by oskari** [Phrynohyas/eve-o-preview#121]
I'd like to keep my thumbnails the same size and instead have like "magnifying glass" kinda of zoom, where the thumbs stay the same but the content is "zoomed". 

Is this technically feasible to implement?

**Comment by Phrynohyas** [comment]
I'm afraid such feature would be a EULA violation. While it is not a violation to display EVE interface as a whole, is a bannable offence to display only part of in in any overlay.
