### ISSUE TITLE
Previews on top-Hide Previews

### ISSUE THREAD

**Issue by iLLeLogical** [Phrynohyas/eve-o-preview#125]
This feature is not working as intended anymore. Even with an other application active & centered the previews stay on top. Have to disable previews on top to be able to do other stuff without eve thumbnails in the way

General | Hide previews when EVE client is not active | Determines whether all thumbnails should be visible only when an EVE client is active
-- | -- | --

**Comment by Phrynohyas** [comment]
Hello. Which exactly version of EVE-O are you using? Is this 4.0.0 or a hotfix 4.0.1 ? The latter one should have this issue fixed

**Comment by iLLeLogical** [comment]
Yes it did mate! Thanks for this great tool :)
