### ISSUE TITLE
when minize inactive client is selected launching that client rescales window without changing resolution

### ISSUE THREAD

**Issue by november781** [Phrynohyas/eve-o-preview#126]
as the title suggests using the thumbnails to launch an inactive client will change the window size without resealing the resolution in-game so unless you run in bordered window mode it is a PITA to fix the window.

running multiple monitors if that helps at all. I don't run Eve on both BC I like to have comms on the other one

**Comment by Phrynohyas** [comment]
Can you create a screenshot / video ?

**Comment by november781** [comment]
it seems to have stopped being an issue, if it pops up again I will create another ticket with a gif link
