### ISSUE TITLE
add option for thumnails to be displayed over full-screen client.

### ISSUE THREAD

**Issue by november781** [Phrynohyas/eve-o-preview#127]
I would love it if the thumbnails would display over a full-screen client

**Comment by Phrynohyas** [comment]
As far I know that would require injecting into EVE process ind interacting with its DirectX calls. Not sure how CCP will react on such intrusion, and not gonna check it.

Fixed Window mode with maximized window looks exactly like FullScreen, so you can use this mode instead.
