### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SleepySnorlax1000** [Phrynohyas/eve-o-preview#134]
o7,

I have been using EVE O Preview a lot recently, however, one thing that keeps bugging me is that I have to rename my JSON files every time I want to get my other layout, so my request would be: Could you maybe add a function to select which file contains the current Loadout for EVE-O Preview (so which file to use as Config JSON)? I know it's not that much work, however, obviously only if you have time to do that, alltegerhter I really like your program 👍

**Comment by Phrynohyas** [comment]
Hello

Well, there are plans for multiple config files.
As for now the easiest workaround if to place several EVE-O Preview .exe copies into different folders and to configure each copy as needed. This will give you several fully independent config files.

EVE-O Preview doesn't write anything to registry or elsewhere outside of its own folder so these copies will be fully independent from each other.
