### ISSUE TITLE
Move config file to writeble location

### ISSUE THREAD

**Issue by wvdvegt** [Phrynohyas/eve-o-preview#137]
In order to correct behavior that is for long flagged as not done anymore (writing in the applications directory (preventing it to be installed in for example program files), I replaced the ConfigurationFileName in ConfigurationStorage by:

```
private readonly static string ConfigurationFileName = Path.Combine(Environment.GetFolderPath(
  Environment.SpecialFolder.ApplicationData), "EVE-O Preview", "EVE-O Preview.json");
```
and GetConfigFileName() in ConfigurationStorage by:

```
        private string GetConfigFileName()
        {
            string filename = string.IsNullOrEmpty(this._appConfig.ConfigFileName) ? ConfigurationStorage.ConfigurationFileName : this._appConfig.ConfigFileName;
            if (!Directory.Exists(Path.GetDirectoryName(filename)))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(filename));
            }
            return filename;
        }
```

This change moves the default EVE-O Preview.json config file to '%appdata%\EVE-O Preview\EVE-O Preview.json".

**Comment by Sakata-MC** [comment]
Please make this an option, though.
I run this as a portable app in its own happy little folder.
Also.... %appdata% isn't as easily accessible to most users, and is annoying to others.

**Comment by wvdvegt** [comment]
Hi

Have to agree, with the previous poster, and having a command-line option to specify a configuration would make it even more versatile.

When having multiple users sharing configuration the location should be changed to:

  `Environment.SpecialFolder.CommonApplicationData`

**Comment by Phrynohyas** [comment]
Way too much hustle to solve a problem that doesn't actually exist
