### ISSUE TITLE
Thumbnail opacity management might cause performance issues and/or app crashes

### ISSUE THREAD

**Issue by itbytes100** [Phrynohyas/eve-o-preview#144]
i am running 6 accounts and was working perfect. not sure now why but when preview is active the game is unplayable, laggy. 

i have tested new driver for 1080, no change 
i have reinstalled windows, no change

Running without eve o preview, eve is running perfect, all 6 spins and runs as per normal.
when eve o preview is running and preview on top is running lag kicks in, when tick is off then work but still laggy. 

but when i click it back on, eve o preview crashes. 

keep up this amazing work 

hope its not a big problem 
ta
sam

**Comment by itbytes100** [comment]
[EVE-O Preview.log](https://github.com/Phrynohyas/eve-o-preview/files/2944486/EVE-O.Preview.log)

sorry this the crash log when i turn it off then back on after testing.

**Comment by Phrynohyas** [comment]
Hello

2 questions:

1. Are your display(s) 144 Hz or 60 Hz ones?
2. Could you try the latest Beta build and see if the problem persists?
2.1. If it does - the could you describe detailed steps how to cause that crash?

TIA

**Comment by itbytes100** [comment]
Hi Phrynohyas, thanks for a quick response, i got the beta just before DT. still same problem.
i have 4 monitors setup 2 at 60 1 and 100 and 1 at 120mhz
i have just done some checking and change monitor to just 1 not the 4 changed from 60 to 120mhz and still laggy on 3 accounts. to me its like a memory leak, only since the eve launcher updated.
Memory used is 14 meg cpu is 2% 

so this is how i start.
Eve o preview 1st
Spyglass 2nd
Eve Launcher 3rd 

Hit launch for all clients 
1 to 6 run with delay 20's

once all at log on screen. mouse is laggy and main screen is lagging. takes a few clicks to hit but once in. it will load. next so on and so on until all 6 are running

i may not always see the preview screen is a static green. no pic. so i will need to reset the software.
if i try to run the 8 its near to impossible to rotate or station spin without laughing, 

once all 6 are up and running i move them to the screen i need, it will lag moving. 

now for my proof its something to do with the software. if i still run it and turn off  the tick for "preview always on top" they 6 clients runs like normal. but when i click it back on it will preview green screen and crash dump. as per below.
[EVE-O Preview.log](https://github.com/Phrynohyas/eve-o-preview/files/2945830/EVE-O.Preview.log)

sorry i have tried many things. 

it was working perfect. only thing that has changed is NVIDIA drivers and Launcher. 

system is intel i7 7700k with 16 gig, 1080 Nvidia. M.2.2 Drive 120gig boot 256 ssd Games 

hope this helps 
ta Sam (ign) Sinister Sam

**Comment by Phrynohyas** [comment]
That's Windows 10 or Window 7 ?
Btw what is 'Spyglass' ?

**Comment by itbytes100** [comment]
Windows 10. Spy glass is intel for 0.0. Vintel. But newer. Also yes tried
with it off too.

**Comment by Phrynohyas** [comment]
Not fun. Could you try out the build attached to this message? I've disabled there all and any opacity settings. Btw I assume all your clients run in window / fixed window mode?

[Eve-O Preview.zip](https://github.com/Phrynohyas/eve-o-preview/files/2946042/Eve-O.Preview.zip)

**Comment by itbytes100** [comment]
yes in windows mode :D will try now

**Comment by itbytes100** [comment]
working a lot faster. i can spin on all 6 toons no lag

**Comment by Phrynohyas** [comment]
So that's opacity that is causing the havoc with performance. I'll implement a proper solution for the next Beta. Not closing the thread as I'll ask you to tray that build too

**Comment by itbytes100** [comment]
Awesome tyvm
