### ISSUE TITLE
[Bug] Thumbnail size settings keep resetting

### ISSUE THREAD

**Issue by Taiphoz** [Phrynohyas/eve-o-preview#153]
The thumbnail windows width and height keeps getting reset, I'v tried setting and saving/exiting the app and re-launching it does not happen every time but eventually I will run it and all my client windows are back in some wide thin size, the position seems fine but the width and height keeps getting reset.

I even tried making the config file read only but that just make the app fail to load.

**Comment by Taiphoz** [comment]
so been living with this annoyance for a while now and iv noticed that when I launch the application it tries to save out a default config file, this resets all my settings, so to get around this I have been setting the file as read only , this works some of the time, but when what ever the reset condition is happens the app just crashes because it cant save to the file.

its annoying pls fix it.

**Comment by Phrynohyas** [comment]
> If you did encounter a bug or a crash please do the following, as this will greatly help me to pin down and fix the possible bug:

> Next to the .exe file there is a configuration .JSON file. Please send it to me via EVE in-game mail. To protect your privacy please replace the name(s) of your alt(s) in the message with something like ‘EVE - Alt 1’ , ‘EVE - Alt 2’, etc before actually sending it out to me.

**Comment by Taiphoz** [comment]
you didnt give me your name, I dont think the issue is with the config file
because it works, the issue is with the client some times trying to write
out a default config file instead of just using the one that already
exists,

but sure give me your in game name and I will mail you the config.

**Comment by Phrynohyas** [comment]
So far you are the only one who reported this.

Trying to write back a default config file could mean that the existing one cannot be properly read.
Actually before sending the file I would suggest you to delete the existing one and to reapply your configuration on a new config file

Also - which exactly EVE-O Preview version you are using?

**Comment by Taiphoz** [comment]
Ok, so yeah I have deleted the config file a bunch of times, that was one
of the first things I did when this started to happen, version 5.0.0 from
the about menu for the version.

So just to be as clear as possible, I can run the app and it works, but
some times every now and then the application for some reason just chooses
to write a fresh file with super thing(wide) windows, I think this all
started to happen after the patch that did something about screen
resolutions or something like that.

is there a verbose debuglog I can turn on ?

**Comment by Phrynohyas** [comment]
Afraid no, there's no debug log. Only a crash-log that is useless in this case.

Do you have more than 1 display? If so then do they have different DPI/scaling set?

**Comment by Phrynohyas** [comment]
Please, post here your config file (don't forget to remove the part with actual char names)

**Comment by Taiphoz** [comment]
Yeah two displays, ones an older standard monitor the main display is wide
screen, so when this thing happens the app makes all the preview windows
into widescreen.

**Comment by Phrynohyas** [comment]
What are their exact resolutions?

Also (since I don't see the config file yet) - I bet you use the mode with thumbnails frames enabled (ie `Overlay` -> `Show frames` is enabled)?

**Comment by Taiphoz** [comment]
{
  "MinimizeToTray": true,
  "ThumbnailRefreshPeriod": 500,
  "CompatibilityMode": false,
  "ThumbnailsOpacity": 1.0,
  "EnableClientLayoutTracking": true,
  "HideActiveClientThumbnail": true,
  "MinimizeInactiveClients": false,
  "ShowThumbnailsAlwaysOnTop": true,
  "HideThumbnailsOnLostFocus": false,
  "EnablePerClientThumbnailLayouts": false,
  "ThumbnailSize": "420, 240",
  "ThumbnailMaximumSize": "960, 540",
  "ThumbnailMinimumSize": "192, 108",
  "EnableThumbnailSnap": true,
  "EnableThumbnailZoom": false,
  "ThumbnailZoomFactor": 2,
  "ThumbnailZoomAnchor": 8,
  "ShowThumbnailOverlays": true,
  "ShowThumbnailFrames": false,
  "EnableActiveClientHighlight": false,
  "ActiveClientHighlightColor": "Yellow",
  "ActiveClientHighlightThickness": 3,
  "PerClientLayout": {},
  "FlatLayout": {
    "EVE -  xxx  ": "-410, 102",
    "EVE -  xxx  ": "-421, 336",
    "EVE -  xxx  ": "-823, 104",
    "EVE": "-368, 120",
    "EVE -  xxx  ": "-421, 819",
    "EVE -  xxx  ": "-421, 578",
    "EVE -  xxx  ": "-1233, 104",
    "EVE -  xxx  ": "-422, 819",
    "EVE -  xxx  ": "-422, 577"
  },
  "ClientLayout": {
    "EVE - xxx": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    },
    "EVE -  xxx   xxx  ": {
      "X": 0,
      "Y": 0,
      "Width": 1920,
      "Height": 1080,
      "IsMaximized": false
    }
  },
  "ClientHotkey": {},
  "DisableThumbnail": {
    "EVE -  xxx   xxx  ": false,
    "EVE -  xxx   xxx  ": false,
    "EVE -  xxx   xxx  ": false,
    "EVE -  xxx   xxx  ": false,
    "EVE -  xxx   xxx  ": false
  },
  "PriorityClients": []
}

**Comment by Queueyou** [comment]
He is not the only one with the issue, I can confirm the same thing

**Comment by Queueyou** [comment]
```
{
  "MinimizeToTray": true,
  "ThumbnailRefreshPeriod": 500,
  "CompatibilityMode": false,
  "ThumbnailsOpacity": 1.0,
  "EnableClientLayoutTracking": true,
  "HideActiveClientThumbnail": false,
  "MinimizeInactiveClients": false,
  "ShowThumbnailsAlwaysOnTop": true,
  "HideThumbnailsOnLostFocus": false,
  "EnablePerClientThumbnailLayouts": false,
  "ThumbnailSize": "668, 251",
  "ThumbnailMaximumSize": "960, 540",
  "ThumbnailMinimumSize": "192, 108",
  "EnableThumbnailSnap": true,
  "EnableThumbnailZoom": false,
  "ThumbnailZoomFactor": 2,
  "ThumbnailZoomAnchor": 0,
  "ShowThumbnailOverlays": true,
  "ShowThumbnailFrames": false,
  "EnableActiveClientHighlight": true,
  "ActiveClientHighlightColor": "GreenYellow",
  "ActiveClientHighlightThickness": 1,
  "PerClientLayout": {},
  "FlatLayout": {
----------Various individual account stuff removed
  }
  "DisableThumbnail": {},
  "PriorityClients": []
}
```

I just keep replacing the auto created 251 with 280:
```
  "ThumbnailSize": "662, 280",
```

Boom, back in business.  Sort of annoying.

**Comment by RX338** [comment]
I'm having the exact same issue. Thumbnail size keeps changeing between logins but not everytime, normally takes a few login/logoff and playing other games inbetween.

**Comment by Sarodh1** [comment]
Same issue here. 

I noticed I have the issue only if I start EVE-O with "char1" client on foreground, then switch to char2.
If I start with "char2" on foreground, the settings do not reset.

For now I'm keeping the file read only, and make sure I start the preview with the correct char on foreground or it crashes. Avoiding to write to a read only file could be a workaround.

1920*1080 display, one screen only, nothing specific on the display.

```
{
  "MinimizeToTray": true,
  "ThumbnailRefreshPeriod": 500,
  "CompatibilityMode": false,
  "ThumbnailsOpacity": 0.77,
  "EnableClientLayoutTracking": false,
  "HideActiveClientThumbnail": true,
  "MinimizeInactiveClients": false,
  "ShowThumbnailsAlwaysOnTop": true,
  "HideThumbnailsOnLostFocus": true,
  "EnablePerClientThumbnailLayouts": false,
  "ThumbnailSize": "320, 180",
  "ThumbnailMaximumSize": "960, 540",
  "ThumbnailMinimumSize": "192, 108",
  "EnableThumbnailSnap": true,
  "EnableThumbnailZoom": false,
  "ThumbnailZoomFactor": 2,
  "ThumbnailZoomAnchor": 0,
  "ShowThumbnailOverlays": true,
  "ShowThumbnailFrames": false,
  "EnableActiveClientHighlight": false,
  "ActiveClientHighlightColor": "GreenYellow",
  "ActiveClientHighlightThickness": 3,
  "PerClientLayout": {},
  "FlatLayout": {
    "EVE - char1": "364, 0",
    "EVE - char2": "363, 0"
  },
  "ClientLayout": {},
  "ClientHotkey": {},
  "DisableThumbnail": {},
  "PriorityClients": []
}
```

When resetting, there are two modified lines :

```
  "ThumbnailsOpacity": 0.76999998092651367,
  "ThumbnailSize": "304, 141",
```

**Comment by Phrynohyas** [comment]
Sigh

Requires a 'resize lock' feature. Under development in the local repository

**Comment by C-O-dE** [comment]
I discovered the same issue(s) with mine, however, the 'fix' is not necessarily an issue with EVE-O, but more with how the EVE profiles are setup, which apparently does not do everything per client/character.  Once I did the following, all the per client setting retention issues went away.

In the EVE launcher, go to one of the Accounts Settings (gear), go to Profiles, click on MANAGE PROFILES
Source: Tranquility > Select Default (do not change anything on the right) > Copy profile (bottom left)
You should now have Default1 - rename it as you choose (so you can remember which profile is for which client)
Repeat this for each of your game logonid clients (not characters)
You should have unique profiles for each session you run, NONE using Default
Now go to the Account Settings/Profiles for each account and select that ID's unique profile
- leave Default as an unused (Master /backup) profile


Hope it helps

Relevant to:  https://github.com/Phrynohyas/eve-o-preview/issues/141
