### ISSUE TITLE
[Feature] Delay on hiding previews

### ISSUE THREAD

**Issue by Phrynohyas** [Phrynohyas/eve-o-preview#167]
Add a configurable delay for option
"Hide previews when EVE client is not active"

**Comment by moldyleftovers** [comment]
I'd like to help implement this feature, is there an approach you already had in mind? I'd like to follow whatever designs/patterns you already follow if possible. I'm also not that familiar with .NET (although I've done lots of other dev) so I'm not sure what the standard approach to something like this would be.

**Comment by Phrynohyas** [comment]
Implemented as part of #185
