### ISSUE TITLE
[Bug] Switching between windows is broken

### ISSUE THREAD

**Issue by Bazzek** [Phrynohyas/eve-o-preview#179]
When i use EVE-O i cannot swap reliably between clients anymore.

It shows the thumbnails and swaps the thumbnails, but the active eve window stays the same.

If i swap windows with the windows taskbar it doesn't work either.

Until i turn eve-o off, then i can swap reliably with the taskbar.

I am fairly sure you want logging of some sort, i'll try to find how to make them for you.

**Comment by Bazzek** [comment]
Okay, close this, it seems to be caused by displayfusion all of a sudden. Turning that off means it now works as expected

**Comment by Phrynohyas** [comment]
3rd party software issue
