### ISSUE TITLE
[Bug] Negative thumbnail coordinates are not allowed

### ISSUE THREAD

**Issue by Phrynohyas** [Phrynohyas/eve-o-preview#181]
https://forums.eveonline.com/t/eve-o-preview-v5-0-1-fua-was-wrong-multi-client-preview-switcher-2020-06-01/4202/604?u=phrynohyas_tig-rah

Odd little bug I found with Eve-O Preview and my weirdo setup:
I have two monitors. The main monitor is 2560 x 1440 and my second monitor is a 1920 x 1080 turned sideways and rotated 90 degrees in the Windows display settings so it is taller than it is wide (so effectively 1080 x 1920). The second monitor is also on the left side of the main monitor. If I create a preview and place it at the top of the second monitor (using negative values in the config file to get it up past 0) then everything works fine as long as I start Eve-O Preview before I start the clients. If I exit Eve-O Preview and restart it with the clients already running or start Eve-O Preview after I’ve started the clients then that first preview at the top of the second monitor will move itself to a lower spot that it wasn’t at previously. It is only the first preview and the others are not affected. Is this related to having to use negative values in the config file for preview coords?

**Comment by vo1** [comment]
I think its related to rotation. I have two displays and it works totally fine for me. All previews on the left display.
What I noticed, however, is when offset left display, and restart EOP - its all going to be messed, all previews getting moved by the amount offsetted. E.g. if you offset display with previews by 500 pixels lower then top preview will move 500 pixels higher and hide behind 0,0 coordinates of display. Looks like some client height/offset bug

**Comment by beach273** [comment]
I have been experiencing a similar issue. Whenever I set a thumbnail with Y < 1 **and**  X < 1 (via drag or config edits), the thumbnail location is reset upon re-opening the program. Y<1 seems to be fine so long as X > 0.

Current workaround is to run a 1 Y for my thumbnails and lose a pixel.
