### ISSUE TITLE
[BUG] Do not save window position of not logged-in clients

### ISSUE THREAD

**Issue by C-O-dE** [Phrynohyas/eve-o-preview#190]
Stage: 
- Primary = Fixed Window @ 2560x1080
- Alts = Windowed @ 1032x768

Just recently, I have had an issue where at startup the Primary is rendering at 2560x1080, but being squished into 1032x768 at the character screen because of this entry in the json:

>    "EVE": {
      "X": 768,
      "Y": 137,
      "Width": 1032,
      "Height": 768,
      "IsMaximized": false
    }

So far, my only recourse has been to shut down EVE-O, launch the primary, log in the character, then relaunch EVE-O, and then the alt group. If I launch EVE-O while Primary is still at character screen (or have to relaunch the Primary), EVE-O again resizes the screen until login. I can close and relaunch the alts all day without issue

The only thing I can think of is to somehow have the basic EVE window(s) be ignored/excluded from EVE-O positioning... ?

_Only other option I can think of is to remove that entry from the json, then make it read only._
-- Strike that. EVE-O "has encountered a problem and needs to close" if the json is read-only.
-- [EVE-O Preview.log](https://github.com/Phrynohyas/eve-o-preview/files/6391756/EVE-O.Preview.log)

**Comment by Phrynohyas** [comment]
It should have not saved the position for default window (and there are checks for it)
So it is definitely a bug, yes
