### ISSUE TITLE
[Bug] Eve-O-Preview windows "falls behind game windows" 

### ISSUE THREAD

**Issue by baldec** [Phrynohyas/eve-o-preview#192]
With the current version (5.1.0) and latest version of windows 10 I am experiencing that the EOP thumbnails keep dissapearing when I click on one to go to one of the other screens. They do not keep in the front when switching from one eve client to another one. And that makes them all dissapear. 

Have not done any depeer research on the matter as of now but I will report it and then if it isn't reproduceable for anyone else I have to look closer to home. i.e. the laptop.

**Comment by Phrynohyas** [comment]
Please send me your config file. Either here or via in-game mail

**Comment by baldec** [comment]
Here you go. Anonymized the toon names

[EVE-O Preview.zip](https://github.com/Phrynohyas/eve-o-preview/files/6460892/EVE-O.Preview.zip)

**Comment by Phrynohyas** [comment]
Try to enable this option: `General -> Previews always on top`. According to your config file it is disabled atm

**Comment by baldec** [comment]
I have found the issue and it was not with EOP. It was with EVE turning off fixed window mode on 5/7 accounts. So whenever I moved to one of the accounts that it had been turned off on it dissapeared ofc.
