### ISSUE TITLE
[Bug] Live preview tiles are not updating

### ISSUE THREAD

**Issue by paxmerlin** [Phrynohyas/eve-o-preview#194]
When I switch clients the live tiles only shows what was last on the screen and do not continue to update. Are the supposed to work this way?

**Comment by Phrynohyas** [comment]
Disable this option: `General -> Minimize inactive EVE clients`
Minimized windows do not redraw themselves, so their "live" preview will be a still image as well

**Comment by paxmerlin** [comment]
awesome, thank you!
