### ISSUE TITLE
[Bug] EVE O Preview will crash when started from Startmenu

### ISSUE THREAD

**Issue by kuch3n** [Phrynohyas/eve-o-preview#198]
If you start EVE O Preview, the configurtaion file won't be loaded. If you move the Thumbnails around, EVE O Preview will crash.

Steps to reproduce:
1. Search for EVE O Preview in Startmenu
2. Start it from there
3. Move around the Thumbnails
4. Crash

It looks like the configuration file won't be loaded, since the working directory is set to somewhere and the setup looks like the standard configuration. The crash could be caused by the auto saving functionaly of EVE O Preview.

**Comment by Phrynohyas** [comment]
Please provide reproduction steps

**Comment by kuch3n** [comment]
> 
> 
> Please provide reproduction steps

updated

**Comment by magnen** [comment]
I can confirm that this is still an issue.

**Comment by Phrynohyas** [comment]
EVE-O Preview doesn't install itself into startmenu.
Check the settings of the ling you created

**Comment by kuch3n** [comment]
You can start it from startmenu which doesn't work, maybe the startmenu is searching for it or whatever. I didn't say there was a link created or similar stuff.

Possible fixes imho
- Add a try/catch block around the implementation for saving the settings
- use AppData to save settings
- change cwd to executable dir
- check for write permissions in cwd and handle read only permissions
