### ISSUE TITLE
[Bug] Launch problem

### ISSUE THREAD

**Issue by Hadonoyon** [Phrynohyas/eve-o-preview#203]
Hello,

My client don't wan to launch and pop up this crash report : 

Newtonsoft.Json.JsonSerializationException: No JSON content found. Path '', line 1, position 3614.
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   à Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   à Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   à EveOPreview.Configuration.Implementation.ConfigurationStorage.Load()
   à EveOPreview.Presenters.MainFormPresenter.LoadApplicationSettings()
   à EveOPreview.Presenters.MainFormPresenter.Activate()
   à EveOPreview.View.MainForm.Show()
   à EveOPreview.Presenter`1.Run()
   à EveOPreview.Program.Main()

Any idea ?

**Comment by Phrynohyas** [comment]
Hey.

Seems the configuration file is corrupted.
Rename the file `EVE-O Preview.json` and try again.

**Comment by Hadonoyon** [comment]
Hello

Thanx for your answer, but it's still not working.

Best regards,

Hado

Le sam. 11 sept. 2021 à 22:59, Anton Kasyanov ***@***.***> a
écrit :

**Comment by Phrynohyas** [comment]
Please send contents of your entire EVE-O Preview folder and installation path. You can send a link to these files via EVE mail if you want to keep them private


TIA

**Comment by Phrynohyas** [comment]
Closing as no one bothered to provide **required** additional info
