### ISSUE TITLE
[Feature] Zoom preview inside bound of frame

### ISSUE THREAD

**Issue by iShaymus** [Phrynohyas/eve-o-preview#207]
I think it would be cool to have an option that zoomed the preview on hover but instead of the preview resizing as per the current zoom mechanic have it zoom within its existing border.

This way when mining for example one could hover over each preview and have the window zoom in to the ore hold or similar.  This can kind of be done with the existing system with careful anchoring but it would be cool if it could be made an actual feature

**Comment by Phrynohyas** [comment]
Not gonna happen.
EVE TOS/EULA explicitly forbid such way of displaying previews. The only allowed preview kind is the one that displays EVE UI entirely and without any changes

**Comment by iShaymus** [comment]
@Phrynohyas I'm not sure if I misunderstood but doesn't ISBoxer offer this functionality and is within the EULA?

**Comment by Phrynohyas** [comment]
ISBoxer also provides input broadcasting feature and (not sure about this) input automation.  Some of ISBoxer features are not compliant with EVE EULA/ToS
