### ISSUE TITLE
Clients are Maximized at launch

### ISSUE THREAD

**Issue by JacobOkanta** [Phrynohyas/eve-o-preview#208]
I have a 4k monitor where I keep 4 clients open and run a total of 8. What I would like to do is have EveO setup with 2 clients in each corner to switch the front window on each corner as opposed to the entire screen. If I launch EveO before or after launching the Eve clients the clients are maximized to fill the screen. Is this doable with EveO or do I need another solution?

**Comment by epoch18** [comment]
First, this project has been pretty abandoned so I wouldn't expect much response. 

Second though, make sure your EVE client video settings aren't set to full screen or any other setting that would cause what you're doing. Next, make sure your EVE-O options are set correctly. There are options there to minimize/hide EVE clients and to remember window locations, etc. You probably also want to check out the "unique layout for each EVE client" options. 

I'd add more to it, but I'm also not exactly sure what you're trying to achieve based on what you explained. Sorry.

**Comment by Phrynohyas** [comment]
> First, this project has been pretty abandoned so I wouldn't expect much response.
@epoch18 
Just trying to mimic the overall EVE Online state
If they screw up on the Fanfest (and most probably they will) then the game will completely die out in 6-9 months (my personal opinion not based on anything)

@JacobOkanta 
EVE can remember client positions and restore them on the next launch. This can be done only for logged-in clients, coz before the login process is completed it is not possible to determine the char /account name without direct reading the client memory (which I obviously won't do)

From the forum topic:

Position changes are gathered on every client activation via thumbnail

Positions are applied on new client startup

Positions are not auto-saved until any other option is changed. IOW if you want to guarantee that updated window positions are saved then f.e. move a thumbnail 1 px to side and back

**Comment by JacobOkanta** [comment]
Thanks for the suggestions. I found the solution. For anyone else needing it I solved the problem by modifying the config file setting "IsMaximised" to false, relaunching, and putting the clients and previews where they belong everything now works as I expected.
