### ISSUE TITLE
Hello, do you have a chance to provide a Chinese version in the future

### ISSUE THREAD

**Issue by banckgg** [Phrynohyas/eve-o-preview#210]
Hello, I'm a Chinese player of Eve. Your software is very easy to use and popular in China, but the language problem has caused some obstacles to some Chinese players. Is it possible to provide a Chinese version in the future?

**Comment by eskwire** [comment]
Hey, he stoped developing this app. so yep I dont think you gonna get that future for know.

**Comment by Phrynohyas** [comment]
There is a topic of the new developer of this app on the official forums.
