### ISSUE TITLE
Possible to add a hotkey to switch/cycle between windows?

### ISSUE THREAD

**Issue by IrationalReticulatingAugment** [Phrynohyas/eve-o-preview#55]
Hello,

Was curious if it would be possible to add a hotkey that would switch/cycle between windows, or has this come up before and would violate eve's tos/eula?

Edit; I'm dumb. Just started browsing through the source and I see you already have a hotkey folder. I'll delete this if I can figure out how.

**Comment by Phrynohyas** [comment]
No need to close - I like this idea.
Current implementation of hotkeys has 2 issues:
1. No GUI to actually SET hotkeys
2. No 'Cycle' key
I'll save this for 2.2 or later release

**Comment by IrationalReticulatingAugment** [comment]
Ok, cool. I've never really used github other than to look at example code before. Apologies if this isn't the right way to go about this.

If I wanted to poke around in the code and understand what's going on, I just fork the project correct? Would it be useful at all if I tried, as someone with almost zero C# knowledge, to get a "cycle" hotkey working? If I can figure out how EOP is finding eve clients to display, I should be able to make it focus on each client in turn, right?

Don't want to step on toes or anything, never contributed to open source projects before, and don't want to be a bother.

**Comment by Phrynohyas** [comment]
I'd invest time in this only if you really want to learn C# and/or WinForms

**Comment by Phrynohyas** [comment]
Rejected. I have a feeling that a key combination to go only thru EVE windows will go way to close to a botting-similar experience. I don't feel it right to implement this.
