### ISSUE TITLE
FPS limiter option

### ISSUE THREAD

**Issue by Grookshank** [Phrynohyas/eve-o-preview#62]
Please consider adding an option, to limit the fps in the preview windows. That would help a lot with the GPU load, when running multiple clients/previews.

**Comment by Phrynohyas** [comment]
There is no 'FPS' in the usual meaning.
EOP doesn't work anyhow with the graphics that EVE puts on-screen. EOP just asks Windows to mirror a window on some surface. It is up to the Win and GPU drives to perform this.
