### ISSUE TITLE
[Feature Request] Window cycling with hotkey

### ISSUE THREAD

**Issue by Shegox** [Phrynohyas/eve-o-preview#81]
Add a hokey to change to the next or prevoius window, this would be handy for multiboxing many of the same characters (f.e. gilas, miners).

Additional some kind of cycle group would be handy (e.g. exclude your Boost/Hauler and cycle only though special toons).

**Comment by Phrynohyas** [comment]
Similar to https://github.com/Phrynohyas/eve-o-preview/issues/55

> Rejected. I have a feeling that a key combination to go only thru EVE windows will go way too close to a botting-similar experience. I don't feel it's right to implement this feature.

We can move the discussion on this to the official forum thread

**Comment by Shegox** [comment]
Okay, thanks for the fast answer though, really awesome tool and we appretiate the work you put into it!
