### ISSUE TITLE
The preview act up weird with 3 accounts at the same time

### ISSUE THREAD

**Issue by dvgamer360** [Phrynohyas/eve-o-preview#86]
This is the first time i am ever using this kind of software. I am trying to setup the preview window's the way i like them but whenever i switch charachters they get stacked or move to random places on my desktop.

Not sure if this something on my part or?

**Comment by Phrynohyas** [comment]
Please send me the configuration file and screenshots if possible.

> ***
>
>When you encounter a bug or a crash please do the following, as this will greatly help me to pin down and fix the possible bug:
>
>Next to the .exe file there is a configuration .JSON file. Please send it to me via EVE in-game mail. To protect your privacy please replace the name(s) of your alt(s) in the message with something like 'EVE - Alt 1' , 'EVE - Alt 2', etc before actually sending it out to me.
>
>***

**Comment by dvgamer360** [comment]
Here is a gif i recorded of the issue:
https://gyazo.com/332df49fd526349fd9906e2579a6d819

This is a screenshot of the preview settings:
https://gyazo.com/7cc89683e6b0ea1ccb2aec2ed1277095

I hope this is what you meant.

**Comment by Phrynohyas** [comment]
No, it is not. Please read my message and provide me the file.

**Comment by Phrynohyas** [comment]
Thanks. I've received the file. Will take care of it "soon" (tm) (probably today or tomorrow)

**Comment by Phrynohyas** [comment]
Cannot repro even on the testcase. Still it might be caused by this: https://github.com/Phrynohyas/eve-o-preview/issues/87
